## CHECK: This is the Makefile.camltk that was installed by ocamltk.
-include $(shell ocamlc -where)/camltk/Makefile.camltk

## CHECK: installation directories
# The first one contains resource files, doc, and the actual binaries for mmm
INSTALLLIBDIR=/usr/local/lib/mmm
# The second one contains the mmm launch script and other binaries
INSTALLBINDIR=/usr/local/bin
MANDIR=/usr/man/man1
MANEXT=1

# This number defines the revision of the applet system
VERSION=418

CAMLC=ocamlc
CAMLOPT=ocamlopt
CAMLYACC=ocamlyacc -v
CAMLLEX=ocamllex
CAMLLIBR=$(CAMLC) -a
CAMLDEP=ocamldep

COMPFLAGS=
LINKFLAGS=
