(*s: ./globals/version.mli *)
(*s: signature Version.number *)
(* Version and other builtin strings *)
val number : int
(*e: signature Version.number *)
(*s: signature Version.http *)
val http : string              (* the version in User-Agent field *)
(*e: signature Version.http *)
(*s: signature Version.about *)
val about : string -> string   (* dialog *)
(*e: signature Version.about *)
(*s: signature Version.initurl *)
val initurl : string -> string (* fake initial url *)
(*e: signature Version.initurl *)
(*s: signature Version.helpurl *)
val helpurl : string -> string (* help url *)
(*e: signature Version.helpurl *)
(*s: signature Version.html *)
val inithtml : string -> string    (* fake initial document *)
(*e: signature Version.html *)
(*s: signature Version.home *)
val home : string -> string    (* MMM home page *)
(*e: signature Version.home *)
(*s: signature Version.applet_init *)
(*-*)
val applet_init : (bool -> unit) ref
(*e: signature Version.applet_init *)
(*e: ./globals/version.mli *)
