SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang ocaml
TOP=../principia/

VERSION=3
DOC=mmm

SRC_ORIG=mmm.nw mmm_extra.nw

SRC= \
  libs/commons/condition.mli\
  libs/commons/condition.ml\
  libs/commons/date.mli\
  libs/commons/date.ml\
  libs/commons/ebuffer.mli\
  libs/commons/ebuffer.ml\
  libs/commons/error.mli\
  libs/commons/error.ml\
  libs/commons/i18nprintf.mli\
  libs/commons/i18nprintf.ml\
  libs/commons/ibtree.mli\
  libs/commons/ibtree.ml\
  libs/commons/lang.mli\
  libs/commons/lang.ml\
  libs/commons/log.mli\
  libs/commons/log.ml\
  libs/commons/low.mli\
  libs/commons/low.ml\
  libs/commons/mlist.mli\
  libs/commons/mlist.ml\
  libs/commons/mstring.mli\
  libs/commons/mstring.ml\
  libs/commons/msys.mli\
  libs/commons/msys.ml\
  libs/commons/i18n.mli\
  libs/commons/i18n.ml\
  libs/commons/munix.ml\
  \
  libs/commons/feed.mli\
  libs/commons/feed.ml\
  tk/glevents.mli\
  tk/glevents.ml\
  libs/commons/hotlist.ml\
  \
  globals/version.mli\
  globals/version.ml\
  \
  url/uri.mli\
  url/uri.ml\
  url/url.mli\
  url/url.ml\
  url/urlenc.mli\
  url/urlenc.ml\
  url/lexurl.mli\
  url/lexurl.mll\
  \
  www/hyper.mli\
  www/hyper.ml\
  www/maps.mli\
  www/maps.ml\
  www/www.mli\
  www/www.ml\
  www/document.mli\
  www/document.ml\
  \
  languages/html/dtd.mli\
  languages/html/dtd.ml\
  languages/html/html.mli\
  languages/html/html.ml\
  languages/html/lexhtml.mli\
  languages/html/lexhtml.mll\
  languages/html/html_eval.mli\
  languages/html/html_eval.ml\
  \
  http/base64.mli\
  http/base64.ml\
  http/http_date.mli\
  http/http_date.ml\
  http/messages.mli\
  http/http_headers.mli\
  http/http_headers.ml\
  http/auth.mli\
  http/auth.ml\
  http/lexheaders.mli\
  http/lexheaders.mll\
  http/retype.mli\
  http/retype.ml\
  http/http.mli\
  http/http.ml\
  \
  protocols/cache.mli\
  protocols/cache.ml\
  protocols/file.mli\
  protocols/file.ml\
  protocols/mailto.ml\
  protocols/protos.mli\
  protocols/protos.ml\
  \
  retrieve/progress.mli\
  retrieve/progress.ml\
  retrieve/retrieve.mli\
  retrieve/retrieve.ml\
  tk/img.mli\
  tk/img.ml\
  retrieve/scheduler.mli\
  retrieve/scheduler.ml\
  \
  viewers/decoders.mli\
  viewers/decoders.ml\
  viewers/embed.mli\
  viewers/embed.ml\
  viewers/save.mli\
  viewers/save.ml\
  viewers/viewers.mli\
  viewers/viewers.ml\
  viewers/plain.ml\
  \
  display/attrs.mli\
  display/attrs.ml\
  display/cmap.ml\
  display/fit.mli\
  display/fit.ml\
  display/fonts.mli\
  display/fonts.ml\
  display/hr.mli\
  display/hr.ml\
  display/htbind.mli\
  display/htbind.ml\
  display/source.mli\
  display/source.ml\
  display/ctext.mli\
  display/ctext.ml\
  display/htmlfmt.ml\
  display/imgload.mli\
  display/imgload.ml\
  display/html_form.mli\
  display/html_form.ml\
  display/htmlw.mli\
  display/htmlw.ml\
  display/form.mli\
  display/form.ml\
  display/html_table.mli\
  display/html_table.ml\
  display/styles.mli\
  display/styles.ml\
  display/table.mli\
  display/table.ml\
  display/htframe.ml\
  display/textw_fo.mli\
  display/textw_fo.ml\
  display/html_disp.mli\
  display/html_disp.ml\
  \
  chrome/about.mli\
  chrome/about.ml\
  chrome/fontprefs.ml\
  chrome/gcache.mli\
  chrome/gcache.ml\
  chrome/plink.mli\
  chrome/plink.ml\
  chrome/prefs.mli\
  chrome/prefs.ml\
  chrome/debug.ml\
  chrome/history.mli\
  chrome/history.ml\
  chrome/nav.mli\
  chrome/nav.ml\
  chrome/mmmprefs.mli\
  chrome/mmmprefs.ml\
  chrome/mmm.mli\
  chrome/mmm.ml\
  chrome/cci.ml\
  \
  main.ml\
  main_remote.ml\
  htparse.ml\
  \
  extensions/audio.ml\
  extensions/images.ml\
  extensions/remove_simple_table.ml\
  extensions/tachy_aftermmm.ml\
  extensions/tachy_space.ml\
  extensions/tachy_test.ml\

#  commons/common.ml\

SRC_VIEWS=${SRC:%=../%}

<latex/mkcommon

index:V:
	$INDEXER -lang cmt $MMMDIR \
    | sed -e 's#main.cmt#Main#' \
    | grep -v 'lib_core/' \
    | grep -v 'external/ocamltk' \
    | grep -v 'i18n/japan' \
    | grep -v 'tk/' \
    | grep -v 'Common.=~' \
    | grep -v 'Common.=:=' \
    > defs_and_uses.list




