SYNCFLAGS=-md5sum_in_auxfile -less_marks -lang ocaml
TOP=../principia/

VERSION=3
DOC=mmm

SRC_ORIG=mmm.nw mmm_extra.nw

SRC= \
  libs/misc/condition.mli\
  libs/misc/condition.ml\
  libs/misc/date.mli\
  libs/misc/date.ml\
  libs/misc/ebuffer.mli\
  libs/misc/ebuffer.ml\
  libs/misc/error.mli\
  libs/misc/error.ml\
  libs/misc/i18nprintf.mli\
  libs/misc/i18nprintf.ml\
  libs/misc/ibtree.mli\
  libs/misc/ibtree.ml\
  libs/misc/lang.mli\
  libs/misc/lang.ml\
  libs/misc/log.mli\
  libs/misc/log.ml\
  libs/misc/low.mli\
  libs/misc/low.ml\
  libs/misc/mlist.mli\
  libs/misc/mlist.ml\
  libs/misc/mstring.mli\
  libs/misc/mstring.ml\
  libs/misc/msys.mli\
  libs/misc/msys.ml\
  libs/misc/i18n.mli\
  libs/misc/i18n.ml\
  libs/misc/munix.ml\
  \
  libs/misc/feed.mli\
  libs/misc/feed.ml\
  gui/tk/glevents.mli\
  gui/tk/glevents.ml\
  libs/misc/hotlist.ml\
  \
  src/globals/version.mli\
  src/globals/version.ml\
  \
  src/url/uri.mli\
  src/url/uri.ml\
  src/url/url.mli\
  src/url/url.ml\
  src/url/urlenc.mli\
  src/url/urlenc.ml\
  src/url/lexurl.mli\
  src/url/lexurl.mll\
  \
  src/www/hyper.mli\
  src/www/hyper.ml\
  src/www/maps.mli\
  src/www/maps.ml\
  src/www/www.mli\
  src/www/www.ml\
  src/www/document.mli\
  src/www/document.ml\
  \
  languages/html/dtd.mli\
  languages/html/dtd.ml\
  languages/html/html.mli\
  languages/html/html.ml\
  languages/html/lexhtml.mli\
  languages/html/lexhtml.mll\
  languages/html/html_eval.mli\
  languages/html/html_eval.ml\
  \
  src/http/base64.mli\
  src/http/base64.ml\
  src/http/http_date.mli\
  src/http/http_date.ml\
  src/http/messages.mli\
  src/http/http_headers.mli\
  src/http/http_headers.ml\
  src/http/auth.mli\
  src/http/auth.ml\
  src/http/lexheaders.mli\
  src/http/lexheaders.mll\
  src/http/retype.mli\
  src/http/retype.ml\
  src/http/http.mli\
  src/http/http.ml\
  \
  src/protocols/cache.mli\
  src/protocols/cache.ml\
  src/protocols/file.mli\
  src/protocols/file.ml\
  src/protocols/mailto.ml\
  src/protocols/protos.mli\
  src/protocols/protos.ml\
  \
  src/retrieve/progress.mli\
  src/retrieve/progress.ml\
  src/retrieve/retrieve.mli\
  src/retrieve/retrieve.ml\
  gui/tk/img.mli\
  gui/tk/img.ml\
  src/retrieve/scheduler.mli\
  src/retrieve/scheduler.ml\
  \
  gui/viewers/decoders.mli\
  gui/viewers/decoders.ml\
  gui/viewers/embed.mli\
  gui/viewers/embed.ml\
  gui/viewers/save.mli\
  gui/viewers/save.ml\
  gui/viewers/viewers.mli\
  gui/viewers/viewers.ml\
  gui/viewers/plain.ml\
  \
  gui/display/attrs.mli\
  gui/display/attrs.ml\
  gui/display/cmap.ml\
  gui/display/fit.mli\
  gui/display/fit.ml\
  gui/display/fonts.mli\
  gui/display/fonts.ml\
  gui/display/hr.mli\
  gui/display/hr.ml\
  gui/display/htbind.mli\
  gui/display/htbind.ml\
  gui/display/source.mli\
  gui/display/source.ml\
  gui/display/ctext.mli\
  gui/display/ctext.ml\
  gui/display/htmlfmt.ml\
  gui/display/imgload.mli\
  gui/display/imgload.ml\
  gui/display/html_form.mli\
  gui/display/html_form.ml\
  gui/display/htmlw.mli\
  gui/display/htmlw.ml\
  gui/display/form.mli\
  gui/display/form.ml\
  gui/display/html_table.mli\
  gui/display/html_table.ml\
  gui/display/styles.mli\
  gui/display/styles.ml\
  gui/display/table.mli\
  gui/display/table.ml\
  gui/display/htframe.ml\
  gui/display/textw_fo.mli\
  gui/display/textw_fo.ml\
  gui/display/html_disp.mli\
  gui/display/html_disp.ml\
  \
  gui/chrome/about.mli\
  gui/chrome/about.ml\
  gui/chrome/fontprefs.ml\
  gui/chrome/gcache.mli\
  gui/chrome/gcache.ml\
  gui/chrome/plink.mli\
  gui/chrome/plink.ml\
  gui/chrome/prefs.mli\
  gui/chrome/prefs.ml\
  gui/chrome/debug.ml\
  gui/chrome/history.mli\
  gui/chrome/history.ml\
  gui/chrome/nav.mli\
  gui/chrome/nav.ml\
  gui/chrome/mmmprefs.mli\
  gui/chrome/mmmprefs.ml\
  gui/chrome/mmm.mli\
  gui/chrome/mmm.ml\
  gui/chrome/cci.ml\
  \
  main/main.ml\
  main/main_remote.ml\
  main/htparse.ml\
  \
  extensions/audio.ml\
  extensions/images.ml\
  extensions/remove_simple_table.ml\
  extensions/tachy_aftermmm.ml\
  extensions/tachy_space.ml\
  extensions/tachy_test.ml\

#  commons/common.ml\

SRC_VIEWS=${SRC:%=../%}

<latex/mkcommon

index:V:
	$INDEXER -lang cmt $MMMDIR \
    | sed -e 's#main.cmt#Main#' \
    | grep -v 'lib_core/' \
    | grep -v 'external/ocamltk' \
    | grep -v 'i18n/japan' \
    | grep -v 'tk/' \
    | grep -v 'Common.=~' \
    | grep -v 'Common.=:=' \
    > defs_and_uses.list




